openapi: 3.0.0
info:
  version: '0.1'
  title: CarHire Car Registration API
  description: API for registrating cars for rental.
  contact:
    name: Mateusz Kołaczyk
    email: mateusz.kolaczyk.97@gmail.com
    url: https://github.com/FIGUS97/
servers:
  - url: 'https://localhost:6001/api'
tags:
  - name: Car
paths: 
  /api/cars:
    get:
      tags:
        - Car
      summary: See all cars filtered.
      description: Asks database to list all cars of chosen brand or/and status of rental.
      parameters:
        - name: brand
          description: A brand of a car.
          in: query
          requied: false
          schema:
            type: string
        - name: status
          description: Sepcifies if the car is available, hidden or rented
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceEntity'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorInformation'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorInformation'
        '404':
          description: Not Found

      